#!/usr/bin/python
import sys
import struct

def main():

    if (len(sys.argv) == 1):
            print "Usage: %s <snes-rom>" % sys.argv[0]
            sys.exit(0)

    filename = sys.argv[1]
    file = open(filename,"rb")

    # print BRK
    file.seek(0xffe6)
    data = file.read(2)
    addr = struct.unpack("<H",data)
    print "BRK: %4x" % addr

    # print NMI
    file.seek(0xffea)
    data = file.read(2)
    addr = struct.unpack("<H",data)
    print "NMI: %4x" % addr

    # print RESET
    file.seek(0xfffc)
    data = file.read(2)
    addr = struct.unpack("<H",data)
    print "RES: %4x" % addr

main()
